services:
  mark:
    image: vlnag/bp_sync
    env_file:
      - .env
    volumes:
      - ./bp_sync/src/logs:/opt/app/logs
    ports:
     - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  mark-migrations:
    image: vlnag/bp_sync
    env_file:
      - .env
    restart: no
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head

  db:
    image: postgres:17.4-bookworm
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 0s
      timeout: 10s

volumes:
  db_data:
