services:
  mark:
    volumes:
      - ./bp_sync/src:/opt/app
    env_file:
      - ./.env
    ports:
     - 8000:8000

  mark-migrations:
    volumes:
      - ./bp_sync/src:/opt/app
    env_file:
      - ./.env

  db:
    ports:
     - 5442:5432
    env_file:
      - ./.env
