"""Add measure

Revision ID: 9e493c09e9f8
Revises: ed25a2b6003e
Create Date: 2025-08-21 12:56:50.810436

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from models.references import MEASURE_VALUES

from .helpers import get_query_for_bulk_insert

# revision identifiers, used by Alembic.
revision: str = "9e493c09e9f8"
down_revision: Union[str, None] = "ed25a2b6003e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measures",
        sa.Column(
            "measure_code",
            sa.Integer(),
            nullable=False,
            comment="Код единицы измерения",
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    # ### end Alembic commands ###
    query = get_query_for_bulk_insert(
        "measures", ["external_id", "name", "measure_code"], MEASURE_VALUES
    )
    op.execute(sa.text(query))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("measures")
    # ### end Alembic commands ###
