"""Add timeline_comment

Revision ID: ed25a2b6003e
Revises: 0dd747f51f2e
Create Date: 2025-08-15 03:55:26.192046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed25a2b6003e"
down_revision: Union[str, None] = "0dd747f51f2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timeline_comments",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата добавления",
        ),
        sa.Column(
            "entity_id",
            sa.Integer(),
            nullable=False,
            comment="ID элемента, к которому привязан комментарий",
        ),
        sa.Column(
            "entity_type",
            sa.String(length=20),
            nullable=False,
            comment="Тип элемента, к которому привязан комментарий",
        ),
        sa.Column("author_id", sa.Integer(), nullable=True, comment="Автор"),
        sa.Column(
            "comment_entity",
            sa.String(),
            nullable=True,
            comment="Текст комментария",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timeline_comments")
    # ### end Alembic commands ###
