"""upd Department add parent

Revision ID: c13a5cdf1d66
Revises: 3f3b5faede58
Create Date: 2025-08-06 14:54:11.349747

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c13a5cdf1d66"
down_revision: Union[str, None] = "3f3b5faede58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "communication_channels",
        "value",
        existing_type=sa.VARCHAR(length=255),
        comment="Значение коннекта",
        existing_comment="Тип коммуникации",
        existing_nullable=False,
    )
    op.add_column(
        "departments", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "departments", "departments", ["parent_id"], ["external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "departments", type_="foreignkey")
    op.drop_column("departments", "parent_id")
    op.alter_column(
        "communication_channels",
        "value",
        existing_type=sa.VARCHAR(length=255),
        comment="Тип коммуникации",
        existing_comment="Значение коннекта",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
