"""Upd delivery_notes

Revision ID: 0dd747f51f2e
Revises: ea2a4bd97553
Create Date: 2025-08-10 18:23:59.981298

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dd747f51f2e"
down_revision: Union[str, None] = "ea2a4bd97553"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_notes",
        sa.Column(
            "date_delivery_note",
            sa.Date(),
            nullable=False,
            comment="Дата накладной в 1с",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("delivery_notes", "date_delivery_note")
    # ### end Alembic commands ###
