"""Add chat_id in Manager

Revision ID: 05471cb803b9
Revises: b251068e8c2d
Create Date: 2025-10-23 15:57:35.449227

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05471cb803b9"
down_revision: Union[str, None] = "b251068e8c2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "managers",
        sa.Column(
            "chat_id",
            sa.Integer(),
            nullable=True,
            comment="ИД служебного чата",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("managers", "chat_id")
    # ### end Alembic commands ###
