"""upd Company model date_last_shipment can None

Revision ID: 3f3b5faede58
Revises: ff90db1e1710
Create Date: 2025-07-24 03:06:54.018955

"""

from typing import Sequence, Union

# import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f3b5faede58"
down_revision: Union[str, None] = "ff90db1e1710"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies",
        "date_last_shipment",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_comment="Дата последней отгрузки",
    )
    op.drop_constraint(
        op.f("fk_companies_lead_id_leads"), "companies", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_companies_contact_id_contacts"),
        "companies",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "companies", "contacts", ["contact_id"], ["external_id"]
    )
    op.create_foreign_key(
        None, "companies", "leads", ["lead_id"], ["external_id"]
    )
    op.drop_constraint(
        op.f("fk_contacts_lead_id_leads"), "contacts", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_contacts_company_id_companies"),
        "contacts",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "contacts", "companies", ["company_id"], ["external_id"]
    )
    op.create_foreign_key(
        None, "contacts", "leads", ["lead_id"], ["external_id"]
    )
    op.drop_constraint(
        op.f("fk_leads_company_id_companies"), "leads", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_leads_contact_id_contacts"), "leads", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "leads", "contacts", ["contact_id"], ["external_id"]
    )
    op.create_foreign_key(
        None, "leads", "companies", ["company_id"], ["external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "leads", type_="foreignkey")
    op.drop_constraint(None, "leads", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_leads_contact_id_contacts"),
        "leads",
        "contacts",
        ["contact_id"],
        ["external_id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        op.f("fk_leads_company_id_companies"),
        "leads",
        "companies",
        ["company_id"],
        ["external_id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_contacts_company_id_companies"),
        "contacts",
        "companies",
        ["company_id"],
        ["external_id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        op.f("fk_contacts_lead_id_leads"),
        "contacts",
        "leads",
        ["lead_id"],
        ["external_id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.drop_constraint(None, "companies", type_="foreignkey")
    op.drop_constraint(None, "companies", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_companies_contact_id_contacts"),
        "companies",
        "contacts",
        ["contact_id"],
        ["external_id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.create_foreign_key(
        op.f("fk_companies_lead_id_leads"),
        "companies",
        "leads",
        ["lead_id"],
        ["external_id"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.alter_column(
        "companies",
        "date_last_shipment",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_comment="Дата последней отгрузки",
    )
    # ### end Alembic commands ###
