"""Add is_frozen and is_setting_source to deal

Revision ID: b0089832362a
Revises: bcf7b2395833
Create Date: 2025-09-01 17:23:49.549043

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import false

# revision identifiers, used by Alembic.
revision: str = "b0089832362a"
down_revision: Union[str, None] = "bcf7b2395833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deals",
        sa.Column(
            "is_frozen",
            sa.Boolean(),
            nullable=False,
            server_default=false(),
            comment="Просроченная сделка заморожена",
        ),
    )
    op.add_column(
        "deals",
        sa.Column(
            "is_setting_source",
            sa.Boolean(),
            nullable=False,
            server_default=false(),
            comment="Источники установлены вручную",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deals", "is_setting_source")
    op.drop_column("deals", "is_frozen")
    # ### end Alembic commands ###
