"""Upd billings

Revision ID: ea2a4bd97553
Revises: c13a5cdf1d66
Create Date: 2025-08-10 12:16:02.761827

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea2a4bd97553"
down_revision: Union[str, None] = "c13a5cdf1d66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billings", sa.Column("document_type", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("billings", "document_type")
    # ### end Alembic commands ###
