"""Add disk_id in model Manager

Revision ID: bcf7b2395833
Revises: 9a0323b54e3b
Create Date: 2025-08-28 14:32:43.389943

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from migration.helpers import get_query_for_bulk_insert
from models.user_models import DEFAULT_COMPANY, MANAGER_VALUES, USERS_VALUES

# revision identifiers, used by Alembic.
revision: str = "bcf7b2395833"
down_revision: Union[str, None] = "9a0323b54e3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "managers",
        sa.Column("disk_id", sa.Integer(), nullable=True, comment="ИД диска"),
    )
    op.alter_column(
        "managers",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="ИД сотрудника",
        existing_comment="ID сотрудника",
        existing_nullable=False,
    )
    op.alter_column(
        "managers",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="Менеджер активный",
        existing_comment="Менеджер работает",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    query = get_query_for_bulk_insert(
        "users",
        ["external_id", "active", "is_online"],
        USERS_VALUES,
    )
    op.execute(sa.text(query))
    query = get_query_for_bulk_insert(
        "companies",
        ["external_id", "title", "revenue", "is_my_company"],
        DEFAULT_COMPANY,
    )
    op.execute(sa.text(query))
    query = get_query_for_bulk_insert(
        "managers",
        ["user_id", "is_active", "default_company_id", "disk_id"],
        MANAGER_VALUES,
    )
    op.execute(sa.text(query))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "managers",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="Менеджер работает",
        existing_comment="Менеджер активный",
        existing_nullable=False,
    )
    op.alter_column(
        "managers",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="ID сотрудника",
        existing_comment="ИД сотрудника",
        existing_nullable=False,
    )
    op.drop_column("managers", "disk_id")
    # ### end Alembic commands ###
