"""Add moved_date to deal

Revision ID: b251068e8c2d
Revises: b0089832362a
Create Date: 2025-10-15 23:17:29.727348

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b251068e8c2d"
down_revision: Union[str, None] = "b0089832362a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deals",
        sa.Column(
            "moved_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата перемещения (резервное поле)",
        ),
    )
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            """
        UPDATE deals
        SET moved_date = COALESCE(moved_time, NOW())
        WHERE moved_date IS NULL
    """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deals", "moved_date")
    # ### end Alembic commands ###
