"""Add models Manager and AdditionalInfo

Revision ID: 9a0323b54e3b
Revises: 9e493c09e9f8
Create Date: 2025-08-28 12:38:46.409523

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a0323b54e3b"
down_revision: Union[str, None] = "9e493c09e9f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managers",
        sa.Column(
            "user_id", sa.Integer(), nullable=False, comment="ID сотрудника"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Менеджер работает",
        ),
        sa.Column("default_company_id", sa.Integer(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["default_company_id"],
            ["companies.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "additional_info",
        sa.Column(
            "deal_id", sa.Integer(), nullable=False, comment="ID сделки"
        ),
        sa.Column(
            "comment",
            sa.String(),
            nullable=False,
            comment="Дополнительная информация",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("additional_info")
    op.drop_table("managers")
    # ### end Alembic commands ###
